USE silent_hill_3_enemies;

-- Insert enemies
INSERT INTO enemies (name, game_appearance, psychological_symbolism, otherworld_behavior) VALUES
  ('Valtiel', 'Silent Hill 3', 'Valtiel does not represent any person''s emotions or subconscious. It is possible that it is a unique being in the Outerworld whose existence is independent of humans, directly serving "God".', 'Valtiel has appeared in different forms prior to Silent Hill 3. The ceremonial robes worn by the figures in the Otherworld elementary school that appeared in Silent Hill were a homage to Valtiel, while Pyramid Head himself was a being or form connected to Valtiel''s existence. Pyramid Head is connected to Valtiel as both of them are described as taking different forms depending on the viewer. A further connection is that Pyramid Head is stated to be the shape of Valtiel''s reason for existence. The Butcher also resembles Valtiel, though possessing a much more violent and bloodthirsty nature; it is unknown whether the two are related beyond superficial similarities.'),
  ('Leonard Wolf', 'Silent Hill 3', 'It is not clear what Leonard''s condition is. He may be a normal human who Heather sees as a monster; this is reinforced by the fact that his voice sounds entirely normal, despite his form. He also emits animal-like grunting at the same time, which doesn''t sound like it belongs to the person talking. Another theory is that he was corrupted by his own madness and the Otherworld, and so became a monster representing his abusive nature towards Claudia. His large, swollen arms may represent that Claudia was physically beaten by them. The slits on his back look like scars from a whip, which might symbolize Claudia feeling anger at her father for abusing her, as well as her desire for him to be punished for doing so. He also may have died, and his soul reformed as a monster in the Otherworld. However, Claudia asks Vincent why he sent Heather to him, perhaps implying that he was still alive, just corrupted to the point of becoming a monster; this is further implied by the gill-like spiracles opened in his back, since only a true living being would have the necessity to breathe while submerged. Regardless, Heather notes that he is not a "person" anymore before killing him.', 'When she encounters Leonard in the flooded basement of the Otherworld hospital, she has a short discussion with him, during which Leonard is hidden from view. Heather is dismayed to find that he too is a follower of the Order, just as Leonard is irate to learn that she is a non-believer. Leonard refuses to part with his treasure, believing it his duty to protect the seal. He rises from the water and reveals himself to be a grisly monster, forcing an exasperated Heather to kill him.'),
  ('The God', 'Silent Hill 3', 'Prior to battling God, Heather jumps down a vertical aperture, which might represent a ruptured vaginal introitus, perhaps one that recently had an episiotomy. This suggests an especially violent and traumatic birth, while the room in which God rests could be seen as the uterus. This may be a metaphor of Heather entering the womb and defeating God before She has the chance and opportunity to be truly "born" into the world. Earlier in the chapel, a painting is seen of God''s followers with a similar-looking cavity in the floor with the caption: "So God hasn''t been lost. We must offer our prayers and not forget our faith. We wait in hope for the day when the path to Paradise will be opened." Directly above the hole leading to God is a painting of Paradise. God is fought deep underground, which could be symbolic that God, or at least the Order''s god, is linked closer to mankind, Hell, or Earth than someplace celestial such as the sky, Heaven, or cosmos. Heather''s battle against God could be seen as a representation of her overcoming her dark past as Alessa and the desire to purge the influence of the Order from the world. It is ambiguous if She is truly a divine being that will bring Paradise or merely another monster manifested by the powers of Silent Hill.', 'The god, also simply called God, is the final boss of Silent Hill 3, encountered at the end of the chapel. She is the result of a partly-failed ritual to resurrect the deity of the town''s religion.'),
  ('Missionary', 'Silent Hill 3', 'The Missionary is a member of the Order that has become monstrous due to Claudia''s power. In Heather''s eyes, the appearance he takes is that of a monster. There is a running theme of maternity and femininity in Silent Hill 3 and its monsters due to the central conflict of the game centering on impregnation in the cult''s attempts to force Heather to birth their god. The combination of the Missionary''s title, his clothing, and his weapons may be seen as a sign of dilation and cutterage, which is the dilation of the cervix and surgical extraction of part of the lining of the uterus and/or contents of the uterus by cutterage (scraping and scooping). "Missionary" here meaning one who is sent on a mission (in this case being a mission to kill, perhaps dually symbolic of being sent to kill Harry, and of a doctor sent to eliminate an unborn fetus); rubber gloves, a mask, and a smock being reminiscent of surgical attire; and the long, sharp weapons being exaggerated imagery of abortion tools. Alternatively, his bladed implements could parallel a penis, phallic object or other instrument that is essential to sexual intercourse or penetration.', 'The Missionary is a major boss from Silent Hill 3. He appears on the roof of Heather Mason''s apartment, having murdered her father not long before in order to enrage her. After a brief and heated conversation, Claudia Wolf commands him to attack Heather.'),
  ('Closer', 'Silent Hill 3', 'In the Order''s chapel, Closers become infested with animated, dark globs moving along their skin, and they are also notably faster. They seem to have a green tinge. The Closer shares similar characteristics of the Mandarin. According to Masahiro Ito, the reason they look similar is because the Mandarin was one of the most underrated monsters of Silent Hill 2. His intentions by them both having similar designs was to imply that their appearance was not just dependent on the person, but that the power of Silent Hill also had some input on the "design" of the monsters.', 'Closer is a creature appearing in Silent Hill 3. Excluding Heather Mason''s dream sequence, this is the first type of monster she encounters. It is seen in a clothing store as it feeds on a woman''s corpse. Heather shoots it to death as it approaches her.'),
  ('Glutton', 'Silent Hill 3', 'According to Lost Memories: Silent Hill Chronicle, the creature''s form is manifested by the Otherworld. The Glutton''s name is attributed to the creature in the story Tu Fui, Ego Eris, which gobbled up knights and villagers who attempted to leave their village. While the creature makes no hostile actions, it nonetheless renders the exit inaccessible to Heather, much like how the creature in the story was an obstacle to the villagers, preventing them from leaving their home. It embodies the fear of helplessness before the circumstances. The fairytale speaks of a priestess that is once killed, resurrected from compassion, and returns to defeat the monster. A possible reason for the Glutton''s indifference towards Heather might be that the priestess in the story is an embodiment of Heather, reborn from Alessa Gillespie out of compassion as well, returning to face the monsters.', 'The Glutton is a monster found in Silent Hill 3. While it is a major obstacle in Heather Mason''s escape from the Otherworld Hilltop Center, it doesn''t pose a legitimate threat to her.'),
  ('Nurse', 'Silent Hill 3', 'According to Lost Memories: Silent Hill Chronicle, the Nurses in Silent Hill 3 may have been human nurses in Brookhaven Hospital that were transformed into monsters, similar to the Puppet Nurses of the original game, but "the details are unclear". Design-wise, creature designer Masahiro Ito describes the Nurse as an amalgamation of the Puppet Nurse and Bubble Head Nurse, but stated that Silent Hill 3 features a different nurse because it has a separate protagonist from the previous games. He clarified that the design does not have a special meaning, but is influenced by Heather''s subconscious memories of Lisa Garland.The third game''s intense, chaotic Otherworld is reflective of Heather''s state of mind, as well as Alessa''s consciousness. The red squares on the Nurse''s mouths are tied to the Otherworld''s fleshy "mouth" squares. "Mouth" represents the "shrieking insanity" from Alessa''s inner turmoil, having suffered at the hands of bullies and the abuse by her mother. The red squares on the Nurse''s faces symbolize inner madness. In Silent Hill 2, the motif of mouths was also used to convey Mary Shepherd-Sunderland''s own shrieking insanity, with the Bubble Head Nurses possessing a floating red square in front of their faces tied to the nine red squares.', 'The Nurses are monsters in Silent Hill 3 encountered by Heather Mason, scattered exclusively throughout Brookhaven Hospital. Though it is unknown whether they are pure manifestations or humans transfigured into monsters, their appearance echoes Heather''s memories of the nurse Lisa Garland and their strange mouths represent Alessa Gillespie''s inner torment. Wielding handguns and iron pipes, the creatures stalk Heather mercilessly as she combs through the hospital, regaining faded memories along the way.'),
  ('Memory of Alessa', 'Silent Hill 3', 'The Memory of Alessa is the imprint of Alessa left in the Otherworld by her powers and mind. It is a manifestation of Alessa''s mind that wants, above all else, to stop "God''s" birth, and to spare the world from the event should it occur, reasoning that a relatively quick death was preferable to the alternate fate. In the center of the carousel is a human figure being burned by fire, symbolic of Alessa''s immolation 24 years ago, as well as her endless torment. The battle also seems to symbolize Heather/Alessa considering suicide, the Memory of Alessa representing the pain, dark emotions, and suffering that make Alessa think it would be better for her to die and her attempts to kill Heather are those dark emotions trying to overwhelm Heather, but her fighting back against the Memory of Alessa represents her determination to keep going and face what will come instead of choosing death.', 'The Memory of Alessa is a boss monster in Silent Hill 3, as well as having her likeness appear in Silent Hill: Revelation. Heather Mason encounters her in the Otherworld''s Lakeside Amusement Park, where combat ensues. She attacks Heather on the carousel after Claudia Wolf confirms that God is currently in Heather''s uterus, feeding off her hatred.'),
  ('Numb Body', 'Silent Hill 3', 'According to Lost Memories: Silent Hill Chronicle, the name "Numb Body" is derived from the creature''s slow and clumsy movements and the pale frozen texture of its body. In contrast to Silent Hill and Silent Hill 2, series creature designer Masahiro Ito only designed five of the monsters in Silent Hill 3. As such, several creature designs were more abstract and created without fully fleshed out symbolism in mind. When asked about the meaning of the Numb Body, Ito replied, "They are only creatures. Sorry."', 'Numb Body is a monster from Silent Hill 3. They also appear in Silent Hill: The Arcade and the comics Dying Inside and Hunger.'),
  ('Double Head', 'Silent Hill 3', 'The Double Heads are a manifestation of Heather''s subconscious, greatly influenced by the image of Alessa Gillespie after she was burned during the ritual to impregnate her with God. They appear with burn scars, wrapped in bandages, and are the first monsters encountered in Silent Hill 3. reature designer Masahiro Ito explained that they placed the creature at the start of the game to convey the protagonist entering a hellish world. The split-jaw design was an homage to Cerberus of Greek mythology and it was intended to seem as though the Double Heads are the watchdogs of Hell. The creature mirrors the Groaners and Split Head, monsters manifested from Alessa''s nightmare from the original game. It is evocative of her strong dislike for dogs.', 'Double Heads are canine monsters in Silent Hill 3 that usually appear in groups of two or four and attack Heather Mason upon sight. They also appear in Silent Hill: The Arcade and Silent Hill: Book of Memories.'),
  ('Pendulum', 'Silent Hill 3', 'According to Lost Memories: Silent Hill Chronicle, the name "Pendulum" is derived from the creature'' method of attack and the way it rotates its body. In contrast to Silent Hill and Silent Hill 2, series creature designer Masahiro Ito only designed five of the monsters in Silent Hill 3. As such, several creature designs were more abstract and created without fully fleshed out symbolism in mind. When asked about the meaning of the Pendulum, Ito stated "Some of creatures from SH3 have nothing special meaning. That is the same."', 'Pendulums are large hovering monsters from Silent Hill 3. They are first encountered in the Central Square Shopping Center and can be found throughout Lakeside Amusement Park and the chapel. In addition to their game appearance, Pendulums are also featured in the Paint It Black comic book.'),
  ('Scraper', 'Silent Hill 3', 'The Scrapers may be actual members of the Order or manifestations of Claudia Wolf''s vision of the Order''s members. The Book of Lost Memories only refers to them as humanoid monsters. They receive their name from their habit of scraping their blades together. It is also very likely that the Scraper is meant to be a frequent reminder of the Missionary. They only appear later in the game, and it is clear that Heather''s fury regarding her father''s murder fails to wane, even resulting in her breaking down sobbing once God is defeated. When Heather encounters the facsimile of her father''s bedroom and leaves, Scrapers are seen in the hallway outside, possibly reminding her of how her father had died. Heather also mentions in the game that since her father is no longer around to do it, she must be who prevails in this massive tribulation. As the player gets closer to the climax, the population of Scrapers increases, supporting this possibility. Also as previously stated, they appear to be a miniature version of the Missionary, and therefore seeing a beast so synonymous would inevitably remind Heather of her father''s murderer. It may also be that the Missionary was a type of Scraper, however, this is not stated anywhere in game.', 'Scrapers are enemies who appear in Silent Hill 3. They are often encountered in the Order''s chapel, very late in the game, and are seen wandering around the hallways.'),
  ('Slurper', 'Silent Hill 3', 'Lost Memories: Silent Hill Chronicle only mentions that they are named for their habit of slurping up the rust-colored blood and bits of flesh that stick to the floor with its pointed bill, so any intended symbolism is left to speculation. Considering their resemblance to well-built human males wearing only shorts or underwear, their habit of surprise attacks and the way they shove Heather to the floor and climb on top of her, their symbolism could be sexual in nature, representing Heather''s possible fear of rapists and stalkers. Heather wears a miniskirt, adding to her vulnerability and the possible sexual theming when a Slurper knocks her down and climbs on top of her. The Slurper''s head with its elongated mouth could be interpreted as being able to reach into her skirt, as well as bearing oral sex and phallic overtones. They have a tendency to grab Heather''s leg and tilt their head up, as if trying to sneak a peek up her skirt. There is a theme of maternity and femininity in Silent Hill 3 and its monsters due to the central conflict of the game centering on impregnation in the Order''s attempts to force Heather to birth their god. The Slurper may adhere to this theme by representing the suction aspiration method of extracting a miscarried or aborted fetus. The creature''s name and snout allude to this, as well as its passive actions in sucking up bodily fluids. The way it knocks Heather on her back when it attacks may be a reference to a woman on her back about to be given suction aspiration treatment. The subject of miscarriage can be tied to fears of problematic pregnancies.', 'Slurpers are crawling humanoid monsters in Silent Hill 3.'),
  ('Split Worm', 'Silent Hill 3', 'The Split Worm is patterned after the Split Head creature that appears in the first game. It is also the first boss of the game, further mirroring the Split Head. The Night Flutter and Wormhead also had worm imagery, and it may reflect Alessa Gillespie''s fear of worms. The boss may also seem to resemble a phallic instrument or a sperm, which is reinforced by the various cavities that the Split Worm enters and exits throughout the battle, something that could be an allusion to sexual intercourse. The teeth in the Split Worm''s mouth may also contribute to this idea, and could possibly reference the myth of vagina dentata. This could point to Heather''s possible reservations or fear of sex in general.', 'Split Worm is a giant monster which attacks Heather Mason at Central Square Shopping Center and the first boss encountered in Silent Hill 3. It is battled in the Otherworld Toluca Lake at the gallows of Toluca Prison in Silent Hill: The Arcade.'),
  ('Insane Cancer', 'Silent Hill 3', 'The Book of Lost Memories claims it represents a "cancer running wild", and its name stems from its cancerous-like appearance. Insane Cancers may also bear similarities to Silent Hill''s very corruption, like an evil cancer spreading throughout the world. They can also illustrate Alessa Gillespie''s re-emergent feelings about herself, that she is a cancer that won''t stay dead. These feelings are also reflected in the message left behind by the Memory of Alessa. Their mimicry of dying, when in reality they are regenerating, may be related to Alessa''s hospitalization; to everyone (other than her mother, Lisa Garland, and Michael Kaufmann), she was dead, when actually she was alive in the hospital and wanted to die, but was unable to due to Dahlia''s incantation and the god in her uterus protecting its mother''s host body.', 'Insane Cancer is an obese humanoid. These abominations, possessing hulking strength, appear in Silent Hill 3. Heather Mason first encounters one sleeping in Hazel Street Station after she picks up a shotgun in an abandoned train car on platform 2. They also appear occasionally in Silent Hill: The Arcade and Silent Hill: Book of Memories. They explode after they are defeated in the latter, making them lethal even in death.');

-- Insert Physical Attributes
INSERT INTO physical_attributes (enemy_id, body_type, size, notable_features) VALUES
  (1, 'Valtiel is humanoid in appearance, but his head vibrates and twitches rapidly, obscuring his facial features; although there are not many features to behold, as his face is blank and leathery, with a series of crude stitches where his mouth should be. His head has a lip-like object on its back, like Glutton or Closer has, and an ear on the left side of the head. He is garbed in ceremonial robes resembling a butcher''s apron and wears gloves. His hands and parts of his body are smudged in what appears to be blood. Valtiel has the Seal of Metatron on both of his shoulders. Metatron and Valtiel are both considered the "Agents of God", and this mark could suggest that Valtiel is in Metatron''s servitude or that he himself is actually Metatron.', 'Large', 'Twitching head, Stitched mouth and leathery facial features. Butcher''s garments and robe.'),
  (2, 'Leonard appears almost reptilian in nature, with a coat of sickly, yellowed skin covering him. His face is mutated and marred beyond recognition, only having a series of holes where his face should be. He has what appears to be black tongues or protrusions in some of the holes. His "hands", his most prominent feature, are a pair of huge, blade-like bone growths that he uses to swipe at Heather. He appears to be amphibious, as he can last almost indefinitely underwater. His human appearance remains unknown.', 'Large', 'Yellowed skin, Mutated face, Blade-like bone growths, Amphibious'),
  (3, 'God appears as a huge, half-skeletal being whose face resembles a cracked porcelain mask with the likeness of Alessa Gillespie: Heather''s previous incarnation and Claudia''s childhood friend. This is likely because the manifestation of God, as previously established in the first Silent Hill, takes on the appearance of what the host, or ritual performer, perceives God to look like. She possesses Alessa''s dark, disheveled hair. Due to God''s unnatural and hasty birth, as well as the hate and anger in Heather''s heart, She is twisted and malformed, with Her legs lacking flesh and ending at the knees. Her spine and pelvis are visible. Much as a baby which has just been born, God seems to possess no intelligence, like - lacking consciousness, sentience and self-awareness. God does not speak in human language, like most monsters, but rather roars like a beast, and Her eyes are always closed, implying that She is blind or asleep. She resembles both Incubus and Incubator, the incarnations of God seen in the end of the first game.', 'Large', 'Porcelain face, Humanoid with quadrupedal movement type, Twisted and malformed. Skeletal silhouette.'),
  (4, 'He is a tall, humanoid monster that seems to be able to comprehend orders. He wears a brown sack over his head and a noose around his neck. The beast wears a set of robes, much like a surgeon''s smock, and has bicep-length rubber gloves stained in blood. Like many other monsters in the game, he is constantly twitching. His weapons of choice are two tonfa-like objects with long blades jutting from the handle. On closer inspection of the boss, he has a human face with an expression of pain. The most notable features are his mouth and nose, leaving his eyes covered and possibly blind. What really sets this fiend apart from other monsters is its human – if rotting and warped – body paired with the intelligence to understand and comply to a direct order (Claudia explains that she commanded it to kill Harry).', 'Medium', 'Brown sack covering the head, blood-stained gloves and a surgeon''s smock. Tonfa blades as weapons.'),
  (5, 'The Closer is a tall, menacing creature, with thick, all-encompassing arms. Some sections of the creature''s arms seem to be stitched together and bandaged up. The Closer''s lips rotate and twitch relentlessly, emanating a wet sound. Two sharp protrusions are held inside the creature''s arms and can be extended outwards much like one uncurls a finger. When attacking, they extend one of these "blades" and thrust it forward rather sluggishly.', 'Medium', 'Large arms with extendable blades that they use to carry out attacks, red outer layer made of stitched up flesh.'),
  (6, 'The Glutton resembles a tall monster encased in decaying skin, trapped within (or part of) a cylindrical cage that surrounds its entire body. The bottom ring of the cage is adorned with an array of sharp spikes, akin to stalagmites, while the top is draped with what appears to be shrouds of the monster''s skin, which may act as a form of tentacle. Features similar to feet can be seen between the spiked prongs, giving the impression that the Glutton is suspended within its cage. The spiked prongs are similar to those in the scenery of the battle with God. The Glutton possesses two mouths that convulse and squirm from its chest and "head". Although initially believed to be eyes, these are confirmed to be mouths; the Tu Fui, Ego Eris fairy tale shows a picture of a knight''s foot extending from the Glutton''s mouth as he is devoured whole. Around the Glutton''s upper head is what appears to be a metal ring. This ring could possibly be mirroring a halo, perhaps alluding to Claudia Wolf''s perspective that the monsters are holy figures created by the Order''s God. From the fairy tale, the Glutton is portrayed as a formidable foe; this would be expected, given the monster''s somewhat aggressive nature and the radio''s emission of static, but the Glutton appears to show no interest whatsoever in attacking Heather.', 'Large', 'Caged mass of decaying skin and flesh. Heavy twitching, no interest in attacking Heather.'),
  (7, 'These nurses have a more "human"-like appearance opposed to those of the past two installments; they lack parasitic growths on their backs like Puppet Nurses, and they have faces unlike Bubble Head Nurses. Their black hair is all uniformly cut into bob cuts, and they share the Bubble Head Nurses'' attire because they are also Brookhaven nurses. The Nurses also appear to have purple eyeshadow and lipstick. Their eyes are always closed. They each have an ambiguous red square-shaped substance around their mouth, implying that they have either coughed up blood or have been feeding on a bloody carcass. This substance could be blood, paint, or make-up. The Bubble Head Nurses in Silent Hill 2 also have red squares over their mouths, which may be an homage. They make heavy panting noises, and when injured, actual screams. They are hunched over with bad posture while making twitching spasms and limp towards Heather.', 'Medium', 'Female humanoids with nurse attires, are equipped with metal pipe with which they use to carry out attacks.'),
  (8, 'The Memory of Alessa appears as a bloody, ragged doppelgänger of Heather, save for Alessa Gillespie''s dark, disheveled hair. Her face and skin are diseased, and the side of her cheek and forehead appear to have its flesh torn off as if melted, a probable reference to Alessa''s burning. Much of her burned and charred skin is peeled off in strips of gored flesh. Her clothes are dirty, bloody, and covered in soot. Her vest is brown instead of Heather''s white, her miniskirt is gray instead of Heather''s green, and her boots are almost black instead of brown. Her turtleneck sweater is black instead of orange. Her movements are twitchy, erratic, and she limps toward Heather.', 'Medium', 'Bloody, ragged doppelgänger of Heather. Her face and skin are diseased. Signs of bodily decay, erratic movements.'),
  (9, 'Numb Bodies are relatively featureless, bipedal creatures that appear in various sizes. They waddle and hop side-to-side. They resemble tadpole-like creatures covered in purplish, pale skin which splits and cracks constantly. They consist of only two legs, which end in deformed, toe-like digits. From their backs protrude two triangular growths of presumably no real purpose. Their heads only have a single hole in it, from which they presumably see, and nothing else.', 'Small', 'White, bird-like creatures with a featureless face, pale skins with red lines of cracks and splits.'),
  (10, 'From the jawline, their heads are split vertically down the middle, with their tongue often hanging lazily between the split halves. Each side of the head seems to function independently as if they are two dogs instead of one. They are "bandaged" in bloody strips of flesh and appear to be horribly burned. One notable aspect is their eyes. The Double Head''s right eye is red and has a visible pupil; its left eye appears grey or blue and lacks a visible pupil, possibly meaning that it is blind in its left eye. When they are attacked by Heather, they sometimes yelp twice instead of once, once for each head.', 'Small', 'Mutt creatures of the Otherworld in Silent Hill 3, rather than having two dog head as the name might suggest, it is a singular head split in half. Bandages seen wrapped around parts of the torso and legs.'),
  (11, 'The Pendulum has the appearance of two human torsos cut in half and connected at their hips by a metal circular device. Its arms are tied and bandaged behind their backs, with each torso facing the opposite direction of the other, and a pair of stilt-like, bladed legs sprout from the center of the mechanical device. It also has a blade attached to each of its heads and rotates its torso (like a pendulum swinging in a single direction) while it moves as an attempt to cut Heather Mason. It makes a horrible, loud screeching sound similar to that of rusty metal grinding, a noise which alters to a sound similar to a broken instrument''s when harmed and grounded.', 'Small', 'Glued human torsos with a set of blades supporting spider-like movement and attacks.'),
  (12, 'They are very similar in appearance and nature to the Missionary, though they are much weaker, as well as less threatening and significantly smaller. They appear as medium-sized humanoid males with dirty brown robes that resemble a butcher''s smock and brown sacks over their faces. They also wear bloody rubber gloves and corduroy pants. Their tonfa-like weapons end in blades, which they constantly scrape together, hence their name.', 'Medium', 'Humanoid males with dirty robes and brown sacks over their heads. Wear bloodied gloves and equipped with tonfa-like weapons.'),
  (13, 'They appear to be men wearing masks and what appear to be leather shorts. Their figure itself is notable by its long, tube-like snouts, much like an anteater''s, which have a mouth with teeth and lips. They have a long tongue with which they use to "slurp" up carrion and blood. Slurpers have club-like front limbs.', 'Small', 'Masked quadrupedals with leather shorts and a tube-like snout. Aneater appearance, club-like front limbs.'),
  (14, 'The Split Worm is a gigantic, vile worm that is covered with a protective, lavender-colored outer layer. This thick skin splits vertically to reveal a fleshy head without any visible eyes or nostrils. It has a massive set of jaws with gigantic teeth, which are its primary attack method. In terms of shape and arrangement, its teeth greatly resemble those of a human adult rather than an animal. It has many strips of gooey flesh connecting its head to the protective layer of skin. While it is massive in size, it is not as long as the word "worm" would suggest.', 'Large', 'Giant limbless worms made of flesh, huge humanoid mouth found at the entrance of its split opening.'),
  (15, 'The name "Insane Cancer" is derived from its outward appearance being reminiscent of a cancerous mass. They are almost completely covered in fatty, bulbous flesh, with pus-like excretions oozing from open sores. Their heads aren''t very distinct, being small bulbs with a wound-like opening as their only feature.', 'Large', 'Bulbous creature with pus-like excretions from body. A small head with minimal features and a large cut penetrating its face.');

-- Insert Movement
INSERT INTO movement (enemy_id, movement_type, speed_level, behavior_pattern) VALUES
  (1, 'Valtiel never confronts Heather directly in combat, so when he does move, it is slow and deliberate.', 'Not Applicable', 'Functions as a guardian or attendant to the “God” within the cult’s theology. Symbolically “operates” the transition between worlds by turning valves, stitching corpses, and appearing when Heather transitions between the normal world and the Otherworld. He is non-hostile and never actively attacks.'),
  (2, 'Moves underwater and Heavy Sprints on-foot', 'Moderate to Fast', 'Relies on powerful melee swipes and grabs. Submerges to close in on Heather’s position, reappearing to land strong attacks.'),
  (3, 'Bound to location of existence', 'Stationary', 'Carry out attacks with upper torso and arms, which are the only body parts that actively move'),
  (4, 'Sprints and Strafes', 'Fast', 'Entirely on-foot, carry out attacks with sprints and lunges closing in the distances'),
  (5, 'Steady Lumbers and Drags', 'Slow to Moderate', 'Uses broad sweeping arm attacks that can knock Heather back. May hiss or produce a guttural roar before attacking. Sometimes emits a strange gas or fluid from its chest area if in range (depending on game version/difficulty).'),
  (6, 'Stationary', 'Not Applicable', 'More of environmental obstacles, not explicited to be able to move as the Glutton is caged. Blocks progress down a corridor until certain conditions (puzzle-related) are met. Constantly “breathes” or chomps in place, but does not chase Heather. Cannot be damaged by conventional means; must be bypassed rather than fought.'),
  (7, 'Sprints and Walks', 'Moderate to Fast', 'Wields weapons like steel pipes or handguns, depending on the specific nurse. Often attacks in small groups, converging on Heather. Demonstrates sporadic, jerky movements and can react to loud noises or close proximity.'),
  (8, 'Bipedal, imitates Heather and her movement', 'Moderate to Fast (Identical to Protagonist)', 'Each form/phase attacks according to the equipped weapon (close-range melee or ranged gunfire). Aggression escalates across phases—she becomes more dangerous when using firearms. Represents Heather’s internal conflict, as she is quite literally a reflection of Alessa’s memories/being.'),
  (9, 'Awkward hops and shuffles', 'Slow to Moderate', 'Usually seen in packs, sometimes swarming or crowding Heather. Can lunge or attempt a quick “pecking” attack if close. In certain areas, they may corner Heather by surrounding her.'),
  (10, 'Quadrupedal', 'Fast', 'Attacks include biting and a lunging pounce. Often appear in small packs, making them more dangerous if Heather is caught off-guard. Their high mobility can make them difficult to shoot without careful timing.'),
  (11, 'Jerky Hovers and Floating', 'Moderate', 'Often found hanging upside-down until it activates and starts spinning around. The unpredictable hovering and rotating can make them tricky to hit with firearms at times.'),
  (12, 'Bipedal, Sidesteps and Jogs', 'Moderate', 'Tends to advance relentlessly but with enough intelligence to evade or block attacks occasionally. Wields a scraping blade (or apparatus) along one arm, attempting close-range slash attacks.'),
  (13, 'Quadrupedal, Erratic Bursts', 'Fast', 'Often tries to knock Heather down to the ground, then continue inflicting damage. Tends to lurk in darker or cluttered areas, occasionally hiding beneath objects. Their low profile can make them hard to spot and harder to aim at with certain weapons.'),
  (14, 'Steady Emerges', 'Slow to Moderate', 'Emerges with a gaping maw split down the middle. Strikes by lunging out of its hole. Weak point is inside its mouth, forcing Heather to time her attacks carefully.'),
  (15, 'Slow lumbers', 'Slow', 'Known for having a large pool of health, making it quite durable. Attacks revolve around brute strength: heavy swings, body slams, or overhead smashes. Appearance embodies a distorted mass of flesh; “cancerous” lumps reflect an unkillable or disease-like presence.');

-- Insert Vulnerabilities
INSERT INTO vulnerabilities (enemy_id, weak_to, resistant_to) VALUES
  (1, 'None', 'Handgun, Shotgun, Katana, Submachine Gun, Steel Pipe, Stun Gun, Knife'),
  (2, 'Shotgun, Handgun, Submachine Gun', 'Knife (Partially), Steel Pipe (Partially), Katana (Partially)'),
  (3, 'Shotgun, Handgun, Katana, Submachine Gun', 'Steel Pipe, Stun Gun, Knife'),
  (4, 'Shotgun, Submachine Gun, Katana', 'Steel Pipe, Stun Gun, Handgun, Knife'),
  (5, 'Shotgun, Handgun, Katana', 'Stun Gun, Steel Pipe, Knife'),
  (6, 'None', 'Shotgun, Submachine Gun, Handgun, Steel Pipe, Katana, Stun Gun, Knife'),
  (7, 'Handgun, Shotgun, Katana, Steel Pipe, Submachine Gun, Stun Gun, Knife', 'None'),
  (8, 'Handgun, Shotgun, Knife, Katana, Steel Pipe, Stun Gun, Submachine Gun', 'None'),
  (9, 'Handgun, Shotgun, Steel Pipe, Katana, Knife, Stun Gun, Submachine Gun', 'None'),
  (10, 'Handgun, Shotgun, Katana, Submachine Gun', 'Stun Gun, Steel Pipe, Knife'),
  (11, 'Submachine Gun, Shotgun, Handgun, Katana', 'Steel Pipe, Stun Gun, Knife'),
  (12, 'Shotgun, Submachine Gun, Katana', 'Knife, Steel Pipe, Stun Gun'),
  (13, 'Shotgun, Handgun, Submachine Gun, Katana, Knife, Steel Pipe', 'None'),
  (14, 'Shotgun, Handgun, Submachine Gun', 'Knife, Steel Pipe, Katana, Stun Gun'),
  (15, 'Shotgun, Handgun, Submachine Gun, Katana, Knife, Steel Pipe', 'None');

-- Insert Attack Patterns
INSERT INTO attack_patterns (enemy_id, attack_name, damage_output, attack_range, attack_speed) VALUES
  (1, 'Not applicable', 'Not applicable', 'Not applicable', 'Not applicable'),
  (2, 'Arm Swings', '15', 'Close Proximity', 'Moderate'),
  (2, 'Double Swipe', '15', 'Close to Moderate Proximity', 'Moderate'),
  (2, 'Underwater Lunge', '25', 'Moderate Proximity', 'Fast'),
  (2, 'Choke', '30', 'Close Proximity', 'Slow'),
  (3, 'Claw Swipe', '20', 'Moderate Proximity', 'Moderate'),
  (3, 'Double Claw Combo', '15', 'Moderate Proximity', 'Moderate'),
  (3, 'Flame Burst', '25', 'Moderate Proximity', 'Moderate'),
  (3, 'Shockwave', '25', 'Moderate Proximity', 'Slow'),
  (4, 'Slash', '15', 'Close to Moderate Proximity', 'Fast'),
  (4, 'Rushing Attack', '18', 'Close Proximity', 'Fast'),
  (4, 'Block/Parry', 'Not Applicable', 'Close Proximity', 'Moderate to Fast'),
  (5, 'Wide Horizontal Swing', '15', 'Moderate Proximity', 'Slow'),
  (5, 'Overhead Slam', '20', 'Close Proximity', 'Slow'),
  (5, 'Chest Spray', '15', 'Very Close Proximity', 'Moderate'),
  (6, 'Not Applicable', 'Not Applicable', 'Not Applicable', 'Not Applicable'),
  (7, 'Pipe Swing', '15', 'Close Proximity', 'Moderate'),
  (7, 'Gunshot', '12', 'Long range Proximity', 'Moderate'),
  (7, 'Lunge (Rare)', '15', 'Close to Moderate Proximity', 'Fast'),
  (8, 'Knife Slash', '12', 'Very Close Proximity', 'Fast'),
  (8, 'Steel Pipe', '18', 'Close to Moderate Proximity', 'Moderate'),
  (8, 'Handgun Shots', '10', 'Long Range Proximity', 'Moderate'),
  (8, 'Submachine Gunshots', '8 per bullet', 'Long Range Proximity', 'Fast'),
  (9, 'Headbutt', '10', 'Very Close Proximity', 'Slow'),
  (9, 'Leap Attack', '10', 'Close to Moderate Proximity', 'Moderate'),
  (10, 'Bite', '12', 'Very Close Proximity', 'Fast'),
  (10, 'Pounce/Lunge', '15', 'Moderate Proximity', 'Fast'),
  (11, 'Blade Spin', '12', 'Close to Moderate Proximity', 'Moderate'),
  (11, 'Blade Lunge/Dive', '15', 'Close to Moderate Proximity', 'Fast'),
  (12, 'Slash', '15', 'Close Proximity', 'Moderate'),
  (12, 'Heavy Swing', '20', 'Moderate to Long Range Proximity', 'Slow'),
  (12, 'Sidestep/Evade', 'Not Applicable', 'Close Proximity', 'Fast'),
  (13, 'Tackle/Ram', '15', 'Close to Moderate Proximity', 'Fast'),
  (13, 'Scrape/Scratch', '10', 'Very Close Proximity', 'Moderate'),
  (14, 'Bite', '20', 'Close Proximity', 'Moderate'),
  (14, 'Ram Emerge', '15', 'Very Close Proximity', 'Fast'),
  (15, 'Swing/Punch', '20', 'Very Close Proximity', 'Slow'),
  (15, 'Body Slam', '25', 'Close Proximity', 'Slow'),
  (15, 'Staggering Flail', '15', 'Close Proximity', 'Slow');

-- Insert Audio Cues
INSERT INTO audio_cues (enemy_id, sound_type, description) VALUES
  (1, 'Faint mechanical grinding, wheezing breath and whisper-like ambience', 'No clear vocalizations, as he never directly engages Heather. When he is nearby, some indistinct sounds of heavy breathing and wheezing.'),
  (2, 'Low growling and pained roars', 'Splashes and gurgling water noises when moving underwater, guttural groaning, especially when he surfaces above the water.'),
  (3, 'Deep, resonant roars, Echoing sounds of shockwave', 'With fire and shockwave attacks God produces a whooshing or rumbling effect. Layered with heavy industrial music during the confrontation.'),
  (4, 'Metallic scraping, ragged hissing and grunts', 'Quick footsteps sounds indicating aggression, Metallic clanging from the blades when it moves for carry out attacks. A ragged, exhaled hiss during confrontations'),
  (5, 'Slow, Echoing Groans', 'Deep echoes of its pained expressions, a heavy dragging from its giant flattened arms. Sometimes a wet, shuffling footstep accompanying its lumbering movement.'),
  (6, 'Gurgling stomach noises, Deep breathing', 'A faint, persistent chomping/chewing or pulsing sound. Heavy breathing behind the door it blocks.'),
  (7, 'Distressed gasps, Quiet mumbling', 'Footstep sounds on hospital floors, noticeable shuffles or clacks if equipped with high heels. If they have a handgun, sounds of gunshots can be heard from long range.'),
  (8, 'Exertion sounds reminiscent of Heather''s', 'When attacking in melee form, she may grunt. Gunfire sounds if she uses a handgun or submachine gun.'),
  (9, 'Soft cooing, high-pitched chirping', 'Muffled squeaking noises, When disturbed or attacking, they produce a short, high-pitched hiss. Footsteps or body-shuffling can be wet or squishy if they crawl or flop around.'),
  (10, 'Snarling and Growling, Distorted Static', 'Distinct panting when idle or if it detects Heather. A sharp yelp when shot or struck.'),
  (11, 'Loud metallic screech or whirring', 'A sustained mechanical "buzz" or hum as it hovers, often telegraphs its presence from a distance with that harsh scraping noise.'),
  (12, 'Harsh grinding, Guttural grunt or growl', 'Metallic scraping of its bladed arms when moving, rapid footsteps sounds when it moves aggressively or sidesteps.'),
  (13, 'Slurping/Licking', 'Quick scuttling noises on all fours, a muffled chittering or scraping when it rushes to knock Heather down.'),
  (14, 'Roaring', 'A wet, slithering noise as it moves through tunnels. Groaning from its split maw when attacking or taking damage.'),
  (15, 'Heavy footfalls, Sluggish groans', 'A gurgling, labored breathing if its stands idle or prepares a slam. Heavy, wet, fleshy footfalls that suggest massive weight.');


INSERT INTO visualizations (enemy_id, image_url, video_url) VALUES
  (1, 'database\Silent Hill 3\images\Valtiel\43602.png', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\Face_cover.webp', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\HilltopCling.webp', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\SHill3_conceptart_dv1N8.webp', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\tumblr_o1cjdqFt7r1sfo1z9o4_r1_640.jpg', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\ValtielArt.webp', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\ValtielElevator.webp', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\ValtielModel.webp', ''),
  (1, 'database\Silent Hill 3\images\Valtiel\ValtielTwist.webp', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\d86bf4b6b25b4c3dba52fba054faafce.jpeg', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\Leonard.webp', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\LeonardLean.webp', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\LeonardModel.webp', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\LeonardPOV.webp', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\LeonardWolf.webp', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\Screenshot 2025-04-19 090753.png', ''),
  (2, 'database\Silent Hill 3\images\Leonard Wolf\Screenshot 2025-04-19 090830.png', ''),
  (3, 'database\Silent Hill 3\images\The God\Fetus.webp', ''),
  (3, 'database\Silent Hill 3\images\The God\God_Model.webp', ''),
  (3, 'database\Silent Hill 3\images\The God\God.webp', ''),
  (3, 'database\Silent Hill 3\images\The God\GodEek.webp', ''),
  (3, 'database\Silent Hill 3\images\The God\GodModel.webp', ''),
  (3, 'database\Silent Hill 3\images\The God\HeatherGod.PNG.webp', ''),
  (3, 'database\Silent Hill 3\images\The God\SH3_God_model.webp', ''),
  (3, 'database\Silent Hill 3\images\The God\ValtielGod.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\Fovy5q7acAA5uiz.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\Fovy6cSacAEEeWh.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\Misionary_003.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\Misionary_007.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\Misionary_008.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\Missionary_Model.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\MissionaryBlock.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\MissionaryGecco2.jpeg.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\MissionaryMonster.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\MissionaryStatue.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\MissionaryWalk.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\Sh3_art_cre_sketch_02.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\TheMissionary.webp', ''),
  (4, 'database\Silent Hill 3\images\Missionary\tumblr_mn6sgsbWyi1qegjq5o4_1280.jpg', ''),
  (4, 'database\Silent Hill 3\images\Missionary\tumblr_mn6sgsbWyi1qegjq5o8_1280.jpg', ''),
  (5, 'database\Silent Hill 3\images\Closer\Closer_lsap.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\closer-2025-concept-art-based-on-ito-sans-sketch-v0-ieqlykzg0mae1.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\Closer.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\Closerart.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\CloserAttack.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\CloserClimb.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\Closerfight.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\CloserModel.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\CloserPipe.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\CloserShoot.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\Dark_Amuse.Park.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\Heather_shoots_a_closer.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\PenShoot.webp', ''),
  (5, 'database\Silent Hill 3\images\Closer\sh3_art_creature_01_closer.jpg', ''),
  (5, 'database\Silent Hill 3\images\Closer\SHill3_conceptart_356oW.webp', ''),
  (6, 'database\Silent Hill 3\images\Glutton\1526559-glutton.jpg', ''),
  (6, 'database\Silent Hill 3\images\Glutton\Glutton.webp', ''),
  (6, 'database\Silent Hill 3\images\Glutton\Glutton2.webp', ''),
  (6, 'database\Silent Hill 3\images\Glutton\GluttonGIF.webp', ''),
  (6, 'database\Silent Hill 3\images\Glutton\GluttonGIF2.webp', ''),
  (6, 'database\Silent Hill 3\images\Glutton\img_e1999.webp', ''),
  (6, 'database\Silent Hill 3\images\Glutton\TheGlutton2.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\3Nurse.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\2171740.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Heather_Shotgun_Nurses.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Nurse_Attacks_02.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Nurse_Fights.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Nurse_render.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Nurse3Face.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Nurse3Model.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\NurseBlock.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\NurseRuns.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\NurseShoot.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Sh3_nurse.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\SH3_square_nurse.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Sh3-nurse-08.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Sh3-nurse-08.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\SH3Nurse.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Silenthill3_screen009.webp', ''),
  (7, 'database\Silent Hill 3\images\Nurse\Twitch.webp', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (8, '', ''),
  (9, '', ''),
  (10, '', ''),
  (10, '', ''),
  (10, '', ''),
  (10, '', ''),
  (10, '', ''),
  (10, '', ''),
  (10, '', ''),
  (10, '', ''),
  (10, '', ''),
  (11, '', ''),
  (12, '', ''),
  (13, '', ''),
  (14, '', ''),
  (15, '', '')
