USE silent_hill_2_enemies;

-- Insert enemies
INSERT INTO enemies (name, game_appearance, psychological_symbolism, otherworld_behavior) VALUES
  ('Pyramid Head or Red Pyramid Thing', 'Silent Hill 2', "Represents the protagonist's repressed guilt and desire for punishment. Its presence embodies a moral reckoning, an executioner.", "In the original game, it appears as a slow relentless stalker in the Otherworld, often emerging from corridors bathed in red hues and decaying textures. Slow and conscious sense of direction towards the protagonist."),
  ('Lying Figures', 'Silent Hill 2', 'They are visual metaphors for repressed memories and guilt. Vague, shifting forms blur the lines of reality and nightmare in Silent Hill 2.', 'They are slow-moving silhouettes that interact dynamically with their respective environments in the Otherworld.'),
  ('Abstract Daddy', 'Silent Hill 2', 'The manifestation of Angela Orosco''s past trauma sustained from her sexually abusive father and brother. Both James and Angela have different visions of Abstract Daddy, as the same trauma is not felt the same by James.', 'First encountered as a boss fight in the Otherworld''s labyrinth, later resurfacing as a less durable enemy type in the hallways of Lakeview Hotel.'),
  ('Flesh Lip', 'Silent Hill 2', 'A reminder of James'' memory of his wife Mary on her deathbed. Its flesh reminiscent of broken skin similarly seen in Mary''s condition.', 'Flesh Lip appears in the retelling of Silent Hill 2 in 2024. James kills one of them in a confrontation in Brookhaven Hospital, after which a second one appears and pulls him into the Otherworld.'),
  ('Mannequin', 'Silent Hill 2', 'The mannequins are one of nine delusions James faces from his subconcious, symbolized by the nine red squares. They represent his natural urges and inclinations regarding inner sexuality. Tubes and other telligible physical features remain a stark reminder of James'' time spent with his hospitalized wife.', ''),
  ('Mandarin', 'Silent Hill 2', 'Mandarins are manifestations of anguish and James''s desire to escape. For this reason, they are not permitted to stand above ground.', 'Mandarins are encountered in the Otherworld, they hang from mesh gratings and attack James with tentacles protruding from orifices resembling a human mouth - a recurring theme throughout Silent Hill 2.'),
  ('Bubble Head Nurse', 'Silent Hill 2', 'The baby face symbolizes James and Mary''s desire for a child. The suffocation that the Nurses experience is also representative of James''s subconscious memory of smothering Mary with a pillow. The red squares covering the mouths symbolize "shrieking insanity," particularly Mary''s anger and verbal abuse against James.', 'The newest rendition of Silent Hill 2 shows Bubble Head Nurses appearing in select chapters with added design elements.'),
  ('Mary (Final Boss)', 'Silent Hill 2', 'When Mary was ill, she had had overwhelming feelings of anger; sorrow; pain; loneliness; helplessness; denial; and a deep disgust with her body, due to her disease. She had felt that her predicament was unfair. As Mary had said in her letter: "When I first learned that I was...going to—die...I just didn''t want to accept it." Mary had been conflicted and confused about her true feelings; she would express her vacillation between wanting, and not wanting, to die. She would also violently lash out at James, as does this boss. The metal lattice probably symbolizes Mary''s sense of confinement then, in her having been invalided and bedridden. Ironically, Mary can also use the tentacle to strangle James, similarly to how he had asphyxiated her. The monster wears some sort of tight headgear meaning her hair is invisible. This could be a reference to Mary''s hair loss caused by her disease. Alternatively, the nun''s habit–like hood may reference Mary and James'' state of forced celibacy due to her illness. The monster wears a dress that is very similar to what the Bubble Head Nurses wear, possibly referencing Mary''s hospitalization.', 'Apppears the final boss in both renditions of Silent Hill 2, integral to different outcomes/endings.');

-- Insert Physical Attributes
INSERT INTO physical_attributes (enemy_id, body_type, size, notable_features) VALUES
  (1, 'Pyramid Head is a figure of James Sunderland''s guilt and inner torment, manifesting from the part of his mind that desires punishment. He is described as a "distorted memory of the executioners" by Takayoshi Sato, who also explains that Silent Hill was once a town of executions. Most of the people living there were either executioners themselves or family to an executioner. A reflection of James, the monster is a masculine humanoid who takes an appearance similar to the executioners of the town''s cult, with a red rusted pyramid-shaped helmet over his head, donning butcher''s wardrobe, leather boots, and white executioner''s gloves. James and Pyramid Head''s shoulders stand at the same height. There is a mark on the back of his garment where the cloth is stitched together, which is a similarity he shares with Valtiel. Exposed from the back-end of the helmet is a bubble-shaped protrusion, the purpose of which is to seal the gap between his neck and helmet. Both the protrusion and the right side of his helmet are made of a substance similar to a dried canvas. The front of the helmet is an iron plate. Underneath it is tongue-like flesh that Pyramid Head uses when attacking James and other monsters. The bottom left corner of the plate will peel up, allowing for the tongue to slither out of the helmet. The helmet itself represents James'' torment, with the sharp corners suggesting the possibility of pain. His Great Knife does not manifest until after James picks up the knife that Angela Orosco was planning to kill herself with, taking the shape of half of a pair of scissors. The intention was for James to find the other half of the scissors (a second Great Knife) in the Labyrinth, symbolizing the connection between him and Pyramid Head. Pyramid Head exists to keep James human and help him realize that he is guilty, often attacking other monsters to fulfill his role. The scene where James hides in the closet from Pyramid Head abusing the Mannequins represents the conflict in his mind. His fear of facing his inner demons manifested itself as Pyramid Head attacking other monsters to remove the visions from his psyche.', 'Large', 'A red, metallic, triangular helmet. A large blade called "Great Knife".'),
  (2, 'The Lying Figures are among the nine creatures tied to the nine red squares. The upper torso is a flesh body bag, corpse-like, from which they writh. Lower body has feminine silhouettes, with feet wearing heels made of flesh.', 'Medium', 'A fleshy portrayal of a corpse. Distinctive features contributing to a female figure.'),
  (3, 'The Abstract Daddy resembles two figures intertwined in an intimate posture over a bed frame. Trapped in this position, the figures are covered with flesh over red hues. What Angela particularly saw in her vision of Abstract Daddy is unique from said physical attributes, deatils of which are ommitted from canon events', 'Large', 'Intertwined fleshy skins tied to a metal bedframe. A human mouth clearly seen from a protruding mound of flesh.'),
  (4, 'Flesh Lip is a creature bound to a grid-like lattice with a mount located on its abdomen. Two feet supporting movement and dislocated arms used for mounting, the entirety of its leg up is a huge mass of flesh. A mouth a the singular facial feature found in the "abdomen" of the fleshy mass.', 'Large', 'Grid-like cage, huge mass of flesh with dislocated arms.'),
  (5, 'The Mannequin appears as sets of upper and lower legs bound to an intermediate torso, resembling that of a mannequin dummy. They lack a fully human appearance because James refuses to remember who they represent or what he did to his late wife. The creatures bare leg braces on each set of their legs, which are similar to the phenolic orthoses that Mary needed to walk during her illness. The creatures have tubes on their abdomens, which are also owed to James'' time spent in the hospital.', 'Medium', 'Mannequin limbs attached to opposite sides of a small torso. No face or upper body silhouette.'),
  (6, 'The Mandarin is a small humanoid with pad-like forearms with attached suctions that they use to hang on mess gratings. The creature has red hues for coloration. In the latest rendition of Silent Hill in 2024, the boss fights show a different version with clear white layers of fabric covering its body', 'Small', 'Small humanoids with suction-pad forearms.'),
  (7, 'Bubble Head Nurses are female humanoid creatures that appear in a low-cut Brookhaven Hospital nurse uniform. Their heads are wrapped in a mask containing largely blood covering their faces. The center of the mask, for some tierations, takes the shape of an infant''s face, sometimes obscured by a red square covered in dried dirt or blood - similarly to the red squares of delusions James experiences.', 'Medium', 'Bloodied nurse figures with obscured faces, masked with vinyl stained by dirt and blood.'),
  (8, 'This version of Mary is her deceased corpse displayed in a metal frame, similarly to Flesh Lip. She is suspended in the frame upside-down, with her head also restricted from a triangular hood resembling that of a Christian nun.', 'Large', 'Mary''s undead corpse suspended in a metal frame, with select clothing inspired by Christian Ideologies.');

-- Insert Movement
INSERT INTO movement (enemy_id, movement_type, speed_level, behavior_pattern) VALUES
  (1, 'Deliberate, slow walks', 'Slow', 'Has a stalking presence, appears when the protagonist''s guilt and inner tormnent peak.'),
  (2, 'Targeted runs at protagonist', 'Moderate to Fast', 'Are scattered around the fog, found commonly in the streets and corridors of Silent Hill.'),
  (3, 'Staggers and slow walks', 'Slow to Moderate', 'The boss fight in Silent Hill 2 remake shows Abstract Daddy in the hallways of the Labyrinth, after James reunites with Angela.'),
  (4, 'Arm Hangs', 'Stationary', 'The boss fight introduces Flesh Lip hanging from the celing with its hand, when taken down we see that it moves around using the metal bars before pulling itself back up where it hung down from.'),
  (5, 'Fast Walks', 'Moderate to Fast', 'The mannequin remains stationary before alerted by James, after which it quickly follows up with attacks at the progtangonist'),
  (6, 'Arm hangs', 'Slow to Moderate', 'The mandarin uses its suction arms to hang and move around the ceiling. Approaches the protagonist when alerted to carry out its attacks.'),
  (7, 'Fast limbs', 'Moderate', 'The Bubble Head Nurse when met by James run towards him with a metal pipe. They use the metal pipe to carry out attacks.'),
  (8, 'Levitated drones and spider crawls', 'Moderate to Fast', 'Mary, as she is tied to the thematic metal frame, levitates in certain phases when in far proximity from James during her confrontation. Addittionally, the metals bars break out of frame, acting like spider legs to support her movement on-ground.');

-- Insert Vulnerabilities
INSERT INTO vulnerabilities (enemy_id, weak_to, resistant_to) VALUES
  (1, 'Firearms, Blunt force', 'Radio detection'),
  (2, 'Firearms, Blunt force', 'None'),
  (3, 'Firearms, Blunt force', 'None'),
  (4, 'Firearms, Blunt force', 'None'),
  (5, 'Firearms, Blunt force', 'Radio detection'),
  (6, 'Firearms, Blunt force', 'None'),
  (7, 'Firearms, Blunt force', 'None'),
  (8, 'Firearms, Blunt force', 'Radio detection');

-- Insert Attack Patterns
INSERT INTO attack_patterns (enemy_id, attack_name, damage_output, attack_range, attack_speed) VALUES
  (1, 'Spear and Knife slashing, Choking and Punching', 'Moderate', 'Melee (Close Proximity)', 'Moderate'),
  (2, 'Acidic Sprays and Tackles', 'Moderate', 'Blunt force (Close Proximity), Mid-range Spit', 'Moderate'),
  (3, 'Grabbing attacks and punching attacks', 'Moderate', 'Blunt force (Moderate Proximity)', 'Fast'),
  (4, 'Strangulation', 'Moderate', 'Asphyxiation (Close Proximity)', 'Moderate'),
  (5, 'Ambush attacks', 'Moderate', 'Blunt force (Close and Mid-Range Proximity)', 'Fast'),
  (6, 'Ambush attacks and Punching', 'Moderate', 'Blunt force (Close Proximity)', 'Fast'),
  (7, 'Metal Pipe Strikes', 'Low to Moderate', 'Blunt force (Close and Mid-Range Proximity)', 'Moderate'),
  (8, 'Tentacle whips, Strangulation and Moth Swarms', 'Moderate to Lethal', 'Blunt force and Asphyxiation (Close and Mid-Range Proximity)', 'Moderate to Fast';

-- Insert Audio Cues
INSERT INTO audio_cues (enemy_id, sound_type, description) VALUES
  (1, 'Footsteps with impending silence', 'Heavy, metallic footsteps and low drones underscore his approach'),
  (2, 'Faint whispers, near silence', 'Squelching and faint groans when they approach the protagonist. Indistinct whispers upon combat/defeat.'),
  (3, 'Heavy metal clanking and Loud Groans', 'Upon movement they collide with debris, cause its metal frame to clatter, Loud screams and groans signalling aggression upon confromtation'),
  (4, 'Heavy metal clanking and High-Pitched Shrieking', 'Collision with debris upon movement causing metal frame to clatter, High-pitched indistinct shrieks when taking damage'),
  (5, 'Plastic Scraping, Muted and irregular dragging noises', 'The mannequin lacks vocal sounds entirely, with audio cues upon contact mainly being the stretching of its outer cover during movements'),
  (6, 'Wet, squelching sounds, Gutteral moaning', 'The Mandarin moves with heavy dragging noises of its flesh. Drowned gurgles and moans upon contact.'),
  (7, 'Jittery footsteps, sharp heel clicks and muffled breathing', 'Upon contact, the Bubble Head Nurse aggressively groans as it carry out attacks. Indistinct whispers can be heard throughout confrontation.'),
  (8, 'Sad, fragmented dialogues interspersed with distorted whispers', 'Her dialogues are sometimes accompanied with soft crying and displays of mental anguish. Upon battle additional metal clanking and moth hisses are introduced');

-- Insert Visualizations
INSERT INTO visualizations (enemy_id, image_url, video_url) VALUES
  (1, 'database\Silent Hill 2\images\Pyramid Head\5y7v6kzkxawjdixw4wqi3c5aebpr.webp', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\4352144-pyramid-1.avif', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\MistyDay.webp', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\Pyramid-Head-Silent-Hil.webp', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\RedPyramidSchool.webp', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\Red_Pyramid.webp', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\Screenshot 2025-04-15 215708.png', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\silent-hill-2-remake-pyramid-head.webp', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\ito_pyramidhead_art_20.jpg', ''),
  (1, 'database\Silent Hill 2\images\Pyramid Head\silent-hill-2-remake-what-is-pyramid-head-s-true-purpose.avif', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\3_uiGrjdV_thumb.detail.png', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\4_XeepPXB_thumb.detail.png', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\755911a558e271de036ec77dd4741612.jpg', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\andrew-pavlovski-lyingfigure3.jpg', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\Contort.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_01.png', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_03.jpg', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_04.jpg', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_05 (1).webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_05.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_06.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_08.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\cre_lying_figure_art_09.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\i-made-a-semi-realistic-render-of-the-lying-figure-in-my-v0-nuqoen9ynix91.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\LF_mod.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\LyingTransparent.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\SH2LyingFigure.webp', ''),
  (2, 'database\Silent Hill 2\images\Lying Figures\Wood_side_hall.webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\Ab1.webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\Abstract_Daddy_YT_t6wjrj.jpg', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\abstractdaddy1.jpg', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\AbstractDaddy1.webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\abstractdaddy2.jpeg', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\Abstractdaddypachislot.webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\Abstractsh2 (1).webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\Abstractsh2.webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\abtracts.webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\cre_abstract_daddy_art_01.jpg', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\cre_abstract_daddy_art_02.webp', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\maxresdefault (1).jpg', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\odd-jorge-views-4.jpg', ''),
  (3, 'database\Silent Hill 2\images\Abstract Daddy\views4.jpg', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\cre_flesh_lip_art_01.jpg', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\cre_flesh_lip_art_02.webp', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\Flesh_Lip_model (1).webp', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\Flesh_Lip_model.webp', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\FleshClose2.webp', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\FleshLip_SH2r_005.webp', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\FleshPachislot.webp', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\FlLips_Model.webp', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\odd-jorge-main-render.jpg', ''),
  (4, 'database\Silent Hill 2\images\Flesh Lip\Screenshot 2025-04-16 001310.png', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\cre_mannequin_art_02.jpg', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\cre_mannequin_art_06.webp', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\cre_mannequin_art_08.webp', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\cre_mannequin_art_09.webp', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\Mannequin_render.webp', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\Mannequin.webp', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\Mnq_mod_01.webp', ''),
  (5, 'database\Silent Hill 2\images\Mannequin\THE_ART_OF_SILENT_HILL_2_-_Mannequin_Concept_Art_2.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\cre_mandarin_01.jpg', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\cre_mandarin_02.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\ImageY.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\Mandarin_Close-Up.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\Mandarin_Enter.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\Mandarin.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\MandarinFence.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\MandarinGround.webp', ''),
  (6, 'database\Silent Hill 2\images\Mandarin\Sh2_screen_020917_07.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\Bubble_Head_Nurse_PR.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\Bubble_Head_render.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_01.jpg', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_02.png', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_04.jpg', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_05.jpg', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_07.jpg', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_08.jpg', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_09.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_11.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_12.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\cre_bubble_head_nurse_art_13.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\DEOCI9aU0AEX1PW.jpeg.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\Hellooo_nurse%21.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\Lone_Nurse.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\Nurse_Mod_01.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\NurseFace.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\NurseFloor.webp', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\silent_hill_2_remake_04.jpg', ''),
  (7, 'database\Silent Hill 2\images\Bubble Head Nurse\silent_hill_2_remake_42.jpg', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\cre_mary_art_01.jpg', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\cre_mary_art_02 (1).webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\cre_mary_art_02.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\Floor.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\MariaBossForm.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\Mary_mod.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\MaryB1.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\MaryBossTransform.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\MaryF.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\MaryInterfered.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\MaryMonster.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\Poses_comparison.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\SH2_Remake_-_Maria_Entering_Into_Phase_Two_Of_Her_Battle.webp', ''),
  (8, 'database\Silent Hill 2\images\Mary (Final Boss)\Strangle.webp', ''),