USE silent_hill_downpour_enemies;

-- Insert enemies
INSERT INTO enemies (name, game_appearance, psychological_symbolism, otherworld_behavior) VALUES
  ('Bogeyman', 'Silent Hill: Downpour', 'The Bogeyman is seen as a ruthless monster in the eyes of those who demonizes his existence. He represents one''s perception of a "monster" based on their respective circumstances. To Murphy, the Bogeyman is both Napier and himself, but to Anne, the Bogeyman appears to be Murphy. In this regard, unlike Pyramid Head, the Bogeyman does not represent a judgment or guilt figure. The Bogeyman may represent the irrational thoughts of an individual''s tendency to demonize another to avoid their own insecurities and misdeeds by placing the blame on the "Bogeyman". When Murphy simply accepted the loss of his son and the futility of his anger towards himself and Napier, he was able to defeat his version of the Bogeyman, retrieving the "freedom" key in the process. This is evidenced by the final stanza of the Bogeyman nursery rhyme: "Take heed, it''s not too late. Mistakes needn''t haunt you forever. Though you have regret, you can''t just forget. You alone decide your fate." In this regard, the Bogeyman represents the notion of self-destruction brought about by revenge and the dehumanization of it, as the relentless pursuit of vengeance can become just as destructive to oneself as that which caused the revenge-seeking behavior in the first place, e.g. both in the form of how Murphy''s life "spiraled out of control" after Napier''s death, and Anne employing whatever means necessary to punish Murphy in order to avenge her father''s death. With Anne, she ended her relationship with Mark Cunningham, diminished her reputation, almost died falling off a cliff, and went through a journey in Silent Hill—all of which could be avoided if Anne let go of her desire for revenge, as difficult as it may be. This idea seems to echo the saying from Confucius "if you are seeking revenge, then first dig two graves". The difference between Murphy and Anne is that Murphy is dealing with the aftermath of killing the Bogeyman, while Anne has not done so yet. It has also been said that Murphy may feel regret (not guilt) about killing Napier.', 'The Bogeyman is an antagonist who appears in Silent Hill: Downpour. He served as Murphy Pendleton''s personal tormentor, akin to that of Pyramid Head or the Butcher, though not as exclusively as the latter two. Murphy encounters him several times throughout his trek through Silent Hill, menacing him on numerous occasions. Beyond Murphy, the Bogeyman also haunted Anne Marie Cunningham, in which she was directly confronted by the monster during the climax of the story. He wields his hammer and follows Murphy and Anne relentlessly. The Bogeyman also appears in the spin-off game Silent Hill: Book of Memories. He stalks the protagonist everywhere (even in Howard''s Shop and the library with the save function) and is temporarily invincible whenever he is clouded by darkness.'),
  ('Doll', 'Silent Hill: Downpour', 'A book of art found in the library, an area densely populated with Dolls, references negative space''s ability to transform the inanimate (the Dolls) into the animate (their Shadows). "Negative Space is an invaluable drawing technique that allows the brain to disconnect from the common shapes and patterns it''s been trained to see, instead focusing on the space around a subject. By focusing on recreating this negative space, rather than the subject, the artist is able to create a much more accurate image. This phenomenon proves that the objects, people, and things we take for granted don''t actually exist as we see them. In fact, they are merely shadows flickering through the empty canvas of the human subconscious". In Anne''s Story, the Dolls seem to be manifestations of Anne''s guilt for cheating on Mark Cunningham with Leonard B. Trent, and her shattered innocence.', 'The Doll is a monster that appears in Silent Hill: Downpour. It attacks by spawning Shadows, translucent silhouettes of the original monster that are capable of movement. They seem to be related to Anne Marie Cunningham.'),
  ('Screamer', 'Silent Hill: Downpour', 'The Screamer may represent: The alarm sirens at Murphy''s prison and how they would ring if he tried to escape his cell, and, by extension, police sirens as well. A murder victim. Her body is covered in decaying flesh, and her screams may reflect the screams that a victim lets out during their struggle. Murphy''s wife, Carol Pendleton, and how she abandoned him. When idle, the Screamer sometimes holds her arms close, rocking back and forth with head slightly tilted, as if cradling a child. This could represent Murphy''s concern about how Carol dealt with Charlie Pendleton''s death and Murphy''s fear of Carol, thinking that she blames and hates him for their son''s death. Thus, he sees the woman he loved now as a woman that is twisted, distorted, and hostile. Part of Sanchez''s psyche, a possible rapist or sexual predator due to the way he treats Anne Marie Cunningham during the bus transfer representing his possible misdeeds. This seems to be supported by his use of derogatory language towards the Screamer ("Bitch!"). The Screamer is not overtly sexual (she has a very flat chest beneath a heavy coat) and this may demonstrate his own predatory nature of possibly forcing sexuality upon them. Sanchez is shown repeatedly beating her face, which is heavily scarred with slashes, and her skin is stretched very tightly as if she has had plastic surgery; this could suggest that Sanchez has previously beaten his victim(s) so badly that they required facial reconstructive surgery. Her flesh-like coat is torn most around where her breasts would be, possibly hinting at a link to sexual violence and sadism. As Murphy displays no signs of sexual aggression, this further supports that she is Sanchez''s monster. Anne Cunningham''s response to her father''s murder. It is given in the game that she is distrustful of Murphy and suspects him to be Frank''s murderer, and the various cutscenes between the two are characterized by volatility. The Screamer''s intense shriek, followed by her vicious attack on Murphy, could be representative of Anne taking out her anger upon the protagonist.', 'The Screamer is a monster in Silent Hill: Downpour and has the ability to stun Murphy Pendleton with a piercing scream. Her attacks vary from concentrated jabs to wild swinging with her fists. She can also alert or call other Screamers to aid her in battle, making her a tough enemy if surrounded.'),
  ('Void', 'Silent Hill: Downpour', 'The Void could be a manifestation of the guilt Murphy feels about his crimes, torturing him for his inability to let go of the past and "running" from his past. In the first Overlook Penitentiary chase sequence, Frank Coleridge''s voice can be heard saying, "You can''t outrun yourself, Murphy," and in the Centennial Building sequence he says, "Truth is like the sun, boy. You can shut it out, but it ain''t going away." It may also represent Murphy''s darker side. While Murphy doesn''t seem to be a particularly violent or aggressive person, his "dark" side pulls him in, threatening to consume him. The Void may be a representation of Murphy''s Thanatos. The Thanatos is a post-Freudian concept of the "death instinct" which embodies the desire to destroy oneself because it is easier to not exist than to have to struggle through life or to accept the guilt and consequences of one''s actions. It may also reflect the painful outcomes of seeking revenge. A book in the Centennial Building discusses the behavior of honey bees and how they will sting an opposing force if pushed to an extreme. It states, "When the bee attempts to flee the scene of the crime, it finds that a large part of its abdomen, guts, nerve, and muscle tissue are torn from its body and left behind. Eviscerated, the bee dies shortly after, paying the ultimate price for revenge." This is very similar to the behavior of the Void stripping the flesh off Murphy. It might be a representation of grief emptiness; when a person has lost someone very dear to them, a situation can occur whenever that person simply shuts down completely, becoming essentially an empty shell. This is the opposite of the effect Charlie Pendleton''s death had on Murphy, but it may perhaps be what Carol Pendleton was feeling inside after her son''s death.', 'The Void, also known as the Shade, is an enemy in Silent Hill: Downpour that resembles a bright red light, similar to a vortex. It pursues Murphy Pendleton relentlessly through the game''s many Otherworld levels and sucks in everything around it. When it gets close to Murphy, the environment visually distorts, time slows down, and Murphy''s body begins to "flake off"; if Murphy doesn''t quickly escape, he will die. The Void cannot be killed, and Murphy''s only option is to flee until he reaches a safe haven. He can also knock over Tormented Souls to slow the Void down and stay farther ahead of it.'),
  ('Monocle Man', 'Silent Hill: Downpour', 'According to Senior Producer Tomm Hulett, Monocle Man represents John P. Sater, or a form thereof.', 'Monocle Man is a monster seen in Silent Hill: Downpour. It verbally torments Murphy Pendleton during their brief and only encounter at the climax of the cavern train ride in Devil''s Pit.'),
  ('Wheelman', 'Silent Hill: Downpour', 'The Wheelman is a manifestation of the memory of Frank Coleridge, and taking into consideration the fact that Murphy must pass through a door with the Scales of Justice hanging above it, then it may also represent Murphy''s feelings of guilt and responsibility over the role he played in Frank''s death. It is possible that the Wheelman represents Murphy''s conscience as well. Because the image of Frank Coleridge frequently appears in Silent Hill as a manifestation of Murphy''s conscience and good nature, the monster''s deteriorated state could embody the erosion of Murphy''s morality based on the poor choices he made following the death of his son, Charlie Pendleton. Anne Marie Cunningham mentions that when her father, Frank, was brutally beaten, he survived the attack but went into a crippled vegetative state and was confined to a wheelchair. She goes on to say that when she looked at him in this state, she saw a monster, or, in this case, Murphy Pendleton. Because of this it''s possible that the Wheelman is actually a manifestation of Anne''s psyche, as opposed to Murphy''s, showing the deterioration of her father and role-model as well as her desire to avenge his death.', 'The Wheelman is the penultimate boss of Silent Hill: Downpour. This monster appears throughout the game in a much lesser form, cloaked in hospital garb, while taunting Murphy Pendleton. It is first seen by Murphy in the window of an abandoned house near Devil''s Pitstop. His non-boss form also appears in Anne''s Story.'),
  ('Prisoner Minion', 'Silent Hill: Downpour', 'The Prisoner Minions represent the frequent fights and riots that prison inmates and prison gangs often participate in while incarcerated, as they are often quite violent struggles that usually end with someone dead. The Prisoner Minions'' eyes are forced open by a metal apparatus extending from the backs of their heads, which also pins their mouth back in a smiling position. This may have connection to controversial administration of intravitreal injections, to drug the more violent subjects into a docile state; which, could be re-enforced by the forceful smile that they portray, symbolizing a state of mind outside of their own control. The smile could also be representative of their initial concept art, which portrayed the prisoners as clowns. The theme of clowns ties in with coulrophobia. Both variations of the Prisoner Minions may be representative of the elements of Murphy''s personality that have changed, become more potent, or arose entirely due to his time in prison. The minions may specifically represent small pieces of his personality attributed to his time as an inmate, such as increased brutality, and willingness to kill.', 'The Prisoner Minion is a monster in Silent Hill: Downpour. They wear a metal contraption on their heads. There are two types of Prisoner Minions: Brawlers and Stabbers. There is a larger, more powerful variant called the Prisoner Juggernaut. One such Juggernaut is shown walking around with a Brawler and a Stabber on "leashes", with meat hooks dug into their backs and being forced to walk around on all fours like dogs, making it very obvious that the Juggernaut is the dominant monster.'),
  ('Weeping Bat', 'Silent Hill: Downpour', 'The Weeping Bats are named after animals of the same name that inhabited the caves of Devil''s Pit. A sign says that they cower in the darkness and are very afraid of lights. It also says that they sometimes attack humans, though there have been no reported casualties. It has been speculated that this monster represents Murphy''s wish to hide from the authorities or to escape from his fate in jail, as observed by the creature being very quick and stealthy. It has also been thought that this monster represents the authority of law enforcement and government officials. An inmate''s time spent in prison contributes to a perceived lack of personal safety and a need to constantly watch their back. At any moment and without warning, they can be attacked on the whim of another inmate. The Weeping Bat may be the embodiment of this mentality; never able to let one''s guard down even for a second, never knowing where a threat may come from. This is supported by their behavior; when found they are often huddled up, but if threatened they stretch up to their full intimidating height to fend for themselves. When standing idle, a lone Weeping Bat tends to look over its shoulders repeatedly as if always expecting someone to sneak up on it. Part of the Weeping Bat''s symbolism is solitary confinement. These are conditions that Murphy might have experienced during his time in prison. It is likely for this reason that they were made to be reclusive, bat-inspired creatures that do their best to stay in the dark and under cover (in Devil''s Pit caves, under bridges, etc.), whose sickly translucent skin suggests that they never see much sunlight. They also seem to represent prison gangs to an extent, as they are quite persistent when it comes to guarding Monocle Man during the train ride almost as if Monocle Man was their gang leader. Alternatively as some creatures, such as the Bogeyman, represent more than one person''s psyche then the Weeping Bats may represent the parents of the children killed in the Devil''s Pit Train crash. The Bats only attack Murphy after he knows the truth about John Sater, and appear most frequently on the train ride. Given how Monocle Man seems to be in constant pain, being splayed out on meat hooks for all to see, they may represent the guilt and torment that binds him to Silent Hill. It is hinted that the "mysterious creatures" that forced the Gillespie Coal & Iron Company to suspend mining operations in Superstition Caverns were Weeping Bats, given the timing of the train''s automated tour guide dialogue and the appearance of a Weeping Bat that suddenly attacks Murphy.', 'Weeping Bat is a monster in Silent Hill: Downpour. It is often very quiet and attaches itself to walls and ceilings, dropping down nimbly behind its prey before attacking.'),
  ('Wall Corpse', 'Silent Hill: Downpour', 'The Wall Corpse continues the theme of Downpour, that of helpless imprisonment, torture, and pain. With the Wall Corpse being impaled in place, in a way it cannot help but attack, in the same way that Murphy initially doesn''t feel he is to blame for the actions which have led to his imprisonment. Like him, it cannot escape its pain and imprisonment and is helpless to do anything but attack and lash out at anybody who comes too close, with the only end to its agony being death. Due to its female frame, it may also symbolize that Murphy is aware of the pain his ex-wife has gone through due to the loss of their son and his own reckless hunt for revenge, while also feeling as if she is attacking him. Indeed, the cavity in its body that it sprays blood from is roughly where a woman''s womb is housed, possibly symbolizing his ex-wife''s child being torn from her in the most painful way possible. Later in the game, as Murphy gets closer to the revelation of his violent actions, the corpses become more mobile, possibly signifying that Murphy realizes he is choosing to attack others.', 'The Wall Corpse is a monster from Silent Hill: Downpour. The creature is possibly related to the Tormented Soul.'),
  ('Tormented Soul', 'Silent Hill: Downpour', 'While being chased by the Void, Murphy can knock over Tormented Souls to slow down the Void. In this respect, the Tormented Souls represent the innocent people who have indirectly suffered due to Murphy''s actions and little regard for others after the death of his son, Charlie Pendleton. In pushing them into the path of the Void, he is essentially sacrificing the defenseless creatures at his own convenience. The Tormented Souls may also be symbolic of Murphy himself. The creatures are confined within a cage, something that could represent how Murphy felt while incarcerated; trapped with only his own guilt. Murphy shoving them into the Void could also be a metaphor for throwing his past behind, something he clearly holds remorse for (this is most directly touched on during his last meeting with the Nun). These creatures also seem to appear to JP Sater as well, revealed in Anne''s Story. They appear alongside twisted manifestations of the eight children who died when he crashed the Devil''s Train, particularly when he articulates to Anne how his nightmares just keep "clawing" away at him until there''s nothing left to fight back with, in life rather. This could very much be symbolized by the way the creatures are trapped within their cages, unable to escape his past. It could also symbolize how he felt when the newspaper''s lies spread further and further around town. The wounds on these creatures could symbolize how damaged or "clawed away" he feels in his day-to-day life, and their lack of limbs may represent to him how he can no longer fight back his pain. The strips of flesh binding them to their cages may also represent how he feels held down by his guilt, and will never be able to move on again. Their lack of any discernible facial features could also subsequently represent how he feels he may no longer have a true face to show people, his positive identity having been, in his eyes, ruined by the press, everyone now believing he is a pathetic and disgusting creature, much like how the Tormented Souls would initially appear.', 'The Tormented Soul is a passive monster in Silent Hill: Downpour and briefly in Anne''s Story. It cannot harm Murphy Pendleton in any way, but it can indirectly kill him by getting in his way while dodging the Void. The creature bears a striking resemblance to the Wall Corpse, indicating that the two may be related.'),
  ('Prisoner Juggernaut', 'Silent Hill: Downpour', 'The Juggernaut could represent Murphy''s fear of the other inmates, or even the inmates themselves, as many, if not all of said inmates could kill or attack Murphy without a second thought while he was in Ryall State Prison. The fact that they appear to have what look like tattoos or prisoner identification numbers on their bodies seems to support this. Both variations of the Prisoner monsters may represent elements of Murphy''s personality that have changed due to his time in prison. The Juggernaut specifically represents a fear Murphy may have developed of himself and the crimes he had committed. It shows a change in his self-image to something more monstrous, and his aversion to them is symbolic of his pent up remorse for his crimes. Their aggression, strength, and dominance could also be a part of their symbolism, as there are cons in every prison who swing some weight by striking deals with other inmates, or with corrupt guards such as George Sewell, in exchange for protection or special favors (e.g. Sewell allowing Pendleton access to Patrick Napier in the sequestered prison shower) which could be symbolized by their pervasiveness, their ability to rip cell doors off hinges, and especially the scene where one Juggernaut is literally holding two Prisoner Minions on a leash.', 'Prisoner Juggernaut is a large, muscular monster in Silent Hill: Downpour. In the first encounter with this monster in Overlook Penitentiary, it is seen ripping off a metal gate so that it can engage Murphy Pendleton. In addition to being encountered in standard monster fights, they can reach through cell bars to grab Murphy as he passes. They are dominant to the smaller Prisoner Minion. On one occasion, a Prison Juggernaut leads two Minions around on meat hook "leashes" like dogs.');

-- Insert Physical Attributes
INSERT INTO physical_attributes (enemy_id, body_type, size, notable_features) VALUES
  (1, 'The Bogeyman appears as a massive humanoid, towering over every other individual in the game. His huge frame is housed in a heavy black raincoat, with his face completely obscured by an S10 gas mask, which is reminiscent of toxic radiation suits. He also wears heavy rubber boots and thick rubber gloves. The coat has several chains, studs, and stitches adorning it. He doesn''t have any immediately recognizable deformities or torture implements in his appearance, unlike almost every other monster in the series—at least none that can be seen with his obscuring coat. The Bogeyman''s signature weapon is a massive sledgehammer, which appears to be made from a cinder block at the end of an elongated fire axe handle.', 'Large', 'Towering male humanoid, wearing a black adorned coat with a large sledgehammer that he uses to carry out attacks.'),
  (2, 'Dolls are nearly stationary monsters, often seen posing like department store mannequins. They are humanoid, resembling a slim woman with pale skin that has a plasticine sheen to it. Dolls are dressed provocatively in a short, dark dress with a bright red or pink bra underneath and sometimes ripped stockings. Some are completely naked except for red liquid splashed across their bodies or their hands. They have platinum blonde or silver hair that is cut in a modern short style. Some Dolls are missing most of their faces, with a large cavity suggesting that their nose, mouth, and jaw have been smashed off. Others have expressions indicative of sex toys, a fact pointed out by Murphy Pendleton when he finds a stationary Doll inside the Centennial Building. They seem to be made of plaster or ceramics, as they will crumble slightly when struck. However, once incapacitated, the Dolls move more organically when struck on the ground. Murphy can also see them running very fluidly as they run well out of harm''s reach. The Shadows of the Doll are perfect silhouettes of the Doll itself, but they are nearly impossible to see. They move in a lunging fashion. Occasionally when illuminated, they will be outlined faintly in white, but this may be a game mechanic to make them easier to battle. It can be noted that the Shadows are slightly easier to see when not looked at directly by the player. Dolls and their shadows also frequently let out soft, wheezing cackles and giggles. When struck, they emit intense moans.', 'Medium', 'Dolls are humanoid doll-like creatures that are mostly stationary. Provocative clothing stained with blood on their hands and from their knees down. Some dolls are naked, some others are missing their faces.'),
  (3, 'The Screamer is humanoid in appearance and resembles a woman wearing a tattered dress and high-heeled boots. They have dark, gray-toned skin with deformed, stretched-tight flesh on their face, inhumanly wide mouths, thin, wispy hair, and empty, bleeding eyes. Screamers'' weapons are their hands, which are permanently affixed in a fist thanks to the several nails driven from the top of their hands through their fingers, which they jab and slash with. Their garb is ripped in many places, exposing tattered flesh underneath. A Screamer''s dress is also hugged close to the figure, as too is the monster''s hair, which suggests her being soaked by rain.', 'Medium', 'Humanoid female, wearing a tattered dress and high-heeled boots. Has deformed, stretched-tight flesh on her face, inhumanly wide mouths, thin, wispy hair, and empty, bleeding eyes. Screamers'' weapons are their hands, which are permanently affixed in a fist thanks to the several nails driven from the top of their hands through their fingers, which they jab and slash with. Their garb is ripped in many places, exposing tattered flesh underneath. A Screamer''s dress is also hugged close to the figure, as too is the monster''s hair, which suggests her being soaked by rain.'),
  (4, 'The Void first appears in the otherworldly Devil''s Pitstop diner. Realizing he can''t fight it, Murphy sprints down a hallway and eventually escapes. He escapes by fleeing up a never-ending staircase where the Void eventually stops pursuing. The Void returns in the Centennial Building Otherworld, chasing Murphy through a looping series of corridors until he finds the right exit. It soon reappears and chases him through an upside-down version of the building. In the Otherworld version of St. Maria''s Monastery, the Bogeyman drops Murphy into a cavernous area where he encounters the Void once again. He runs through another circuitous route before finding a hidden path that leads back to the upper levels. During the game''s climactic sequence at Overlook Penitentiary, the Void appears immediately after the prison''s shift to the Otherworld and chases Murphy through a maze of branching corridors. The entity reappears near the end of the Otherworld, at a series of staircases going up past several tiers of cell blocks. Once Murphy reaches the elevator taking him down to the Wheelman''s room, the Void disappears for good.', 'Large', 'An unquantified mass of red bright light that has a tendency to follow up on the protagonist. Unknown intentions towards Murphy, possibly to kill him.'),
  (5, 'This monster resembles a draped face stretched tightly outward with hooks, chains, and even train tracks, with pale skin and a searchlight worn as a monocle on its left eye. Monocle Man possesses the ability to talk, asking Murphy if he enjoyed his ride through the caverns.', 'Large', 'A giant mass of flesh with one side resebling a draped face stretched with hooks, chains, and train tracks. Possess a monocle on its left eye, as the name might suggest.'),
  (6, 'The Wheelman resembles a giant, emaciated corpse fused with a wheelchair and life-support machinery. The underside of the ribcage/stomach area is largely exposed and has numerous tubes and machinery plugged into it. It also has plentiful segments of wire and metal fused into its body. Its face is completely mutilated into a pulpy mass, with a horribly tumor-like growth on one half of its face and a single papery eye on the other half. It has skinny, atrophied legs which seem to be tied to its wheelchair and can only be seen when it writhes in pain. Huge tanks of blood surround its environment, as well as clear fluids and gigantic air-pumps.', 'Large', 'Giant abomination resembling a half split human body set on a wheelchair, metal cords and wires exposed in its interior.'),
  (7, 'Prisoner Minions appear to be dark-skinned, tortured humanoids covered in tattoos and lacerations. They all wear ragged brown pants secured with a cord. Their most distinctive feature however, is the series of metal framework digging into their face. These metal strips stretch their faces, forcing open their blank white eyes and keeping their mouths taut into inhumanly huge open-mouthed grins. The straps appear to be bolted to their heads, and blood constantly drips from their mouths, covering their necks and chests. Stabbers are even more deformed, with withered left arms and the flesh of their knife-wielding hand mutated and fused into a tumorous lump. They display a lot of violent twitching, having quick spasms and convulsions from the waist up constantly. When left idle and unaware of Murphy Pendleton''s presence, they appear to grapple with their restraints, trying in vain to remove them.', 'Medium', 'Tortured humanoid figures found with tattoos and large lacerations on their bodies. A metal contraption on their heads, restricting them from blinking and closing their mouths, leaving a permanent, ear-to-ear smile with their pupils completely dilated.'),
  (8, 'This creature has grayish-toned skin, with sunken and deformed areas of flesh on its face. It has a massive mouth with what seems to be a huge cleft in its upper lip, and tiny eyes sunken deep into its flesh. Similar to many bat species, its face overall appears to be "pinched," or tight. The upper torso is heavily defined with muscle, while its appendages remain very thin. Weeping Bats are massive creatures with their legs reaching Murphy Pendleton''s shoulders. They attack with their three-clawed hands, with similar ones on their feet which they use to cling to rock. Some Weeping Bats have pinkish skin mottled with deep red vein-like patterns.', 'Large', 'Twisted humanoid with various bodily mutations and deformations. It has a massive mouth with what seems to be a huge cleft in its upper lip. Upper torso is defined with muscles, while the appendages remain thin.'),
  (9, 'The Wall Corpse is a disemboweled human torso that appears female, since it lacks any male genitalia and has a female shape. However, it is not highly sexualized regardless, and thus its gender remains ambiguous. It has been dismembered of all four limbs and is impaled on a metal contraption with large spikes, which looks like the Halo of the Sun, a representative symbol of the Order. It screams in agony as it sprays blood from its lower body, which damages Murphy.', 'Medium', 'Human torsos that are diassembled of all four limbs, impaled with a metal contraption with large spikes representing the symbol of the Order.'),
  (10, 'The Tormented Souls resemble mangled, humanoid bodies that are ripped apart and suspended by their own flesh in grated crates. They writhe in torment and agony, but cannot escape by any means. They have a great deal of blood about themselves, which is most likely their own. The creature''s face appears to be frozen in a look of terror and great pain.', 'Medium', 'Caged mass of flesh severely deformed and mutated. Indistinctly human, although horribly maimed and destroyed.'),
  (11, 'Juggernauts look very similar to the smaller Minions, appearing as pale-skinned humans with tattoos covering their bodies and their faces twisted into permanent grins. They lack the metal contraptions of the Minions, but have barbed wire wrapped loosely around their midsections and tightly around their arms instead. It appears that this barbed wire is threaded into their faces as well, keeping their expression frozen and leaving deep indentations in their flesh. True to their name, Juggernauts are huge and inhumanly strong, with muscular physiques.', 'Large', 'Larger, stronger versions of the Prisoner Minions, with barbed wire wrapped loosely around their midsections and tightly around their arms instead. It appears that this barbed wire is threaded into their faces as well, keeping their expression frozen and leaving deep indentations in their flesh.');

-- Insert Movement
INSERT INTO movement (enemy_id, movement_type, speed_level, behavior_pattern) VALUES
  (1, 'Slow plodding', 'Slow to Moderate', 'Wanders around his area-of-effect, deliberate movements with a relentless stature.'),
  (2, 'Stationary', 'Stationary', 'She has limited movement range, only relying on her loud sobbing and cries to lure in Murphy. Once the protagonist is in range, she laughs and spawns Shadows.'),
  (3, 'Sidesteps and Sprints', 'Moderate to Fast', 'She is rather swift in movement, similarly to her speed of attacking. Natural resolve to dodging attacks and sidesteps, making her a dangerous enemy type.'),
  (4, '', '', ''),
  (5, '', '', ''),
  (6, '', '', ''),
  (7, '', '', ''),
  (8, '', '', ''),
  (9, '', '', ''),
  (10, '', '', ''),
  (11, '', '', '');

-- Insert Vulnerabilities
INSERT INTO vulnerabilities (enemy_id, weak_to, resistant_to) VALUES
  (1, '', ''),
  (2, '', ''),
  (3, '', ''),
  (4, '', ''),
  (5, '', ''),
  (6, '', ''),
  (7, '', ''),
  (8, '', ''),
  (9, '', ''),
  (10, '', ''),
  (11, '', '');

-- Insert Attack Patterns
INSERT INTO attack_patterns (enemy_id, attack_name, damage_output, attack_range, attack_speed) VALUES
  (1, '', '', '', ''),
  (2, '', '', '', ''),
  (3, '', '', '', ''),
  (4, '', '', '', ''),
  (5, '', '', '', ''),
  (6, '', '', '', ''),
  (7, '', '', '', ''),
  (8, '', '', '', ''),
  (9, '', '', '', ''),
  (10, '', '', '', ''),
  (11, '', '', '', '');

-- Insert Audio Cues
INSERT INTO audio_cues (enemy_id, sound_type, description) VALUES
  (1, '', ''),
  (2, '', ''),
  (3, '', ''),
  (4, '', ''),
  (5, '', ''),
  (6, '', ''),
  (7, '', ''),
  (8, '', ''),
  (9, '', ''),
  (10, '', ''),
  (11, '', '');